apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: nodeapp
          servicePort: 80
